/*
 * Copyright (C) 2019  Consiglio Nazionale delle Ricerche
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU Affero General Public License as
 *     published by the Free Software Foundation, either version 3 of the
 *     License, or (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU Affero General Public License for more details.
 *
 *     You should have received a copy of the GNU Affero General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.20 at 05:17:49 PM CEST 
//


package it.cnr.jada.firma.jaxb;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "documentoOrTestoDelMessaggio",
        "allegati",
        "note"
})
@XmlRootElement(name = "Descrizione")
public class Descrizione {

    @XmlElements({
            @XmlElement(name = "Documento", required = true, type = Documento.class),
            @XmlElement(name = "TestoDelMessaggio", required = true, type = TestoDelMessaggio.class)
    })
    protected List<Object> documentoOrTestoDelMessaggio;
    @XmlElement(name = "Allegati")
    protected Allegati allegati;
    @XmlElement(name = "Note")
    protected String note;

    /**
     * Gets the value of the documentoOrTestoDelMessaggio property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentoOrTestoDelMessaggio property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentoOrTestoDelMessaggio().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Documento }
     * {@link TestoDelMessaggio }
     */
    public List<Object> getDocumentoOrTestoDelMessaggio() {
        if (documentoOrTestoDelMessaggio == null) {
            documentoOrTestoDelMessaggio = new ArrayList<Object>();
        }
        return this.documentoOrTestoDelMessaggio;
    }

    /**
     * Gets the value of the allegati property.
     *
     * @return possible object is
     * {@link Allegati }
     */
    public Allegati getAllegati() {
        return allegati;
    }

    /**
     * Sets the value of the allegati property.
     *
     * @param value allowed object is
     *              {@link Allegati }
     */
    public void setAllegati(Allegati value) {
        this.allegati = value;
    }

    /**
     * Gets the value of the note property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setNote(String value) {
        this.note = value;
    }

}
