/*
 * Copyright (C) 2019  Consiglio Nazionale delle Ricerche
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU Affero General Public License as
 *     published by the Free Software Foundation, either version 3 of the
 *     License, or (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU Affero General Public License for more details.
 *
 *     You should have received a copy of the GNU Affero General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.20 at 05:17:49 PM CEST 
//


package it.cnr.jada.firma.jaxb;

import jakarta.xml.bind.annotation.*;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "denominazioneOrNomeOrCognomeOrTitoloOrCodiceFiscale",
        "identificativo"
})
@XmlRootElement(name = "Persona")
public class Persona {

    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute(name = "rife")
    @XmlIDREF
    protected Object rife;
    @XmlElements({
            @XmlElement(name = "Denominazione", required = true, type = Denominazione.class),
            @XmlElement(name = "Nome", required = true, type = Nome.class),
            @XmlElement(name = "Cognome", required = true, type = Cognome.class),
            @XmlElement(name = "Titolo", required = true, type = Titolo.class),
            @XmlElement(name = "CodiceFiscale", required = true, type = CodiceFiscale.class)
    })
    protected List<Object> denominazioneOrNomeOrCognomeOrTitoloOrCodiceFiscale;
    @XmlElement(name = "Identificativo")
    protected String identificativo;

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the rife property.
     *
     * @return possible object is
     * {@link Object }
     */
    public Object getRife() {
        return rife;
    }

    /**
     * Sets the value of the rife property.
     *
     * @param value allowed object is
     *              {@link Object }
     */
    public void setRife(Object value) {
        this.rife = value;
    }

    /**
     * Gets the value of the denominazioneOrNomeOrCognomeOrTitoloOrCodiceFiscale property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the denominazioneOrNomeOrCognomeOrTitoloOrCodiceFiscale property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDenominazioneOrNomeOrCognomeOrTitoloOrCodiceFiscale().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Denominazione }
     * {@link Nome }
     * {@link Cognome }
     * {@link Titolo }
     * {@link CodiceFiscale }
     */
    public List<Object> getDenominazioneOrNomeOrCognomeOrTitoloOrCodiceFiscale() {
        if (denominazioneOrNomeOrCognomeOrTitoloOrCodiceFiscale == null) {
            denominazioneOrNomeOrCognomeOrTitoloOrCodiceFiscale = new ArrayList<Object>();
        }
        return this.denominazioneOrNomeOrCognomeOrTitoloOrCodiceFiscale;
    }

    /**
     * Gets the value of the identificativo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIdentificativo() {
        return identificativo;
    }

    /**
     * Sets the value of the identificativo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIdentificativo(String value) {
        this.identificativo = value;
    }

}
