/*
 * Copyright (C) 2019  Consiglio Nazionale delle Ricerche
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU Affero General Public License as
 *     published by the Free Software Foundation, either version 3 of the
 *     License, or (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU Affero General Public License for more details.
 *
 *     You should have received a copy of the GNU Affero General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.20 at 05:17:49 PM CEST 
//


package it.cnr.jada.firma.jaxb;

import jakarta.xml.bind.annotation.*;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "intestazione",
        "riferimenti",
        "descrizione"
})
@XmlRootElement(name = "Segnatura")
public class Segnatura {

    @XmlAttribute(name = "versione")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String versione;
    @XmlAttribute(name = "xml:lang")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String xmlLang;
    @XmlElement(name = "Intestazione", required = true)
    protected Intestazione intestazione;
    @XmlElement(name = "Riferimenti")
    protected Riferimenti riferimenti;
    @XmlElement(name = "Descrizione", required = true)
    protected Descrizione descrizione;

    /**
     * Gets the value of the versione property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVersione() {
        if (versione == null) {
            return "2001-05-07";
        } else {
            return versione;
        }
    }

    /**
     * Sets the value of the versione property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVersione(String value) {
        this.versione = value;
    }

    /**
     * Gets the value of the xmlLang property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getXmlLang() {
        if (xmlLang == null) {
            return "it";
        } else {
            return xmlLang;
        }
    }

    /**
     * Sets the value of the xmlLang property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setXmlLang(String value) {
        this.xmlLang = value;
    }

    /**
     * Gets the value of the intestazione property.
     *
     * @return possible object is
     * {@link Intestazione }
     */
    public Intestazione getIntestazione() {
        return intestazione;
    }

    /**
     * Sets the value of the intestazione property.
     *
     * @param value allowed object is
     *              {@link Intestazione }
     */
    public void setIntestazione(Intestazione value) {
        this.intestazione = value;
    }

    /**
     * Gets the value of the riferimenti property.
     *
     * @return possible object is
     * {@link Riferimenti }
     */
    public Riferimenti getRiferimenti() {
        return riferimenti;
    }

    /**
     * Sets the value of the riferimenti property.
     *
     * @param value allowed object is
     *              {@link Riferimenti }
     */
    public void setRiferimenti(Riferimenti value) {
        this.riferimenti = value;
    }

    /**
     * Gets the value of the descrizione property.
     *
     * @return possible object is
     * {@link Descrizione }
     */
    public Descrizione getDescrizione() {
        return descrizione;
    }

    /**
     * Sets the value of the descrizione property.
     *
     * @param value allowed object is
     *              {@link Descrizione }
     */
    public void setDescrizione(Descrizione value) {
        this.descrizione = value;
    }

}
